### ISSUE TITLE
Error in Commerce checkout on upgrading from version 12 to version 13

### ISSUE THREAD

**Issue by Ramya-Devendiran** [umbraco/Umbraco.Commerce.Checkout#20]
In local environment, the order creation is working fine and it navigates to the confirmation page correctly. But in the live application that is deployed in azure is not working. It is giving below error on assembly version of Microsoft.Extensions.Identity.Stores. Please guide to fix the issue.
Umbraco CMS 13.5.2
Umbraco.Commerce 13.1.10 / 13.1.13
Umbraco.Commerce.Checkout 13.1.1 / 13.1.2

We are using UMBRACO trial version.

Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
error CS1705: Assembly 'Umbraco.Infrastructure' with identity 'Umbraco.Infrastructure, Version=13.5.2.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.Identity.Stores, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Identity.Stores' with identity 'Microsoft.Extensions.Identity.Stores, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
 ...
   at Umbraco.Cms.Web.Common.Controllers.RenderController.Index()
   at Umbraco.Commerce.Checkout.Web.Controllers.UmbracoCommerceCheckoutCheckoutStepPageController.Index()

**Comment by mattbrailsford** [comment]
Duplicate issue https://github.com/umbraco/Umbraco.Commerce.Issues/issues/596
